def root = new File(basedir.toString())
def report = new File(root, ".blastradius/last-build-report.json").getText("UTF-8")
def log = new File(root, "build.log").getText("UTF-8")

assert report.contains('"mode":"SELECT"')
assert report.contains('"selectedCount":2')
assert report.contains('"totalCount":3')
assert report.contains('"reason":"DEPENDENCY_MATCH"')
assert report.contains('"reason":"NEW_OR_MODIFIED_TEST"')
assert log.contains("[blastradius] SELECT")
assert log.contains("[blastradius] 2 / 3 tests selected")
assert new File(root, "target/surefire-reports/TEST-example.FooTest.xml").isFile()
assert new File(root, "target/surefire-reports/TEST-example.NewTest.xml").isFile()
assert !new File(root, "target/surefire-reports/TEST-example.BarTest.xml").exists()
